WITH FISH_TABLE AS (
    SELECT I.FISH_TYPE, N.FISH_NAME
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
)

SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_TABLE
GROUP BY FISH_TYPE, FISH_NAME
ORDER BY FISH_COUNT DESC;
