WITH VALID_CAR AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
),
RENT_FIVE AS (
    SELECT CAR_ID
    FROM VALID_CAR
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM VALID_CAR
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM RENT_FIVE
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC;