SELECT SE.YEAR, (SE.MAX_COLONY - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) SE
ON YEAR(E.DIFFERENTIATION_DATE) = SE.YEAR
ORDER BY 1, 2;