WITH BEST_EMPLOYEE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
    ORDER BY SCORE DESC
    LIMIT 1
)

SELECT B.SCORE, H.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM HR_EMPLOYEES H
JOIN BEST_EMPLOYEE B
ON H.EMP_NO = B.EMP_NO;
